[GNSS-SDR]

GNSS-SDR.internal_fs_sps=20460000

; =========================
; Signal Source: USRP / UHD
; =========================
SignalSource.implementation=UHD_Signal_Source
SignalSource.item_type=gr_complex
SignalSource.sampling_frequency=20460000
SignalSource.freq=1207140000

SignalSource.gain=40

SignalSource.otw_format=sc16

SignalSource.IF_bandwidth_hz=20460000

SignalSource.repeat=false
SignalSource.samples=0
SignalSource.dump=false
SignalSource.enable_throttle_control=false

; SignalSource.device_serial=XXXXXXXX

; SignalSource.device_address=addr=192.168.10.2


; =========================
; Signal Conditioner
; =========================
SignalConditioner.implementation=Pass_Through

DataTypeAdapter.implementation=Pass_Through

InputFilter.implementation=Pass_Through
InputFilter.input_item_type=gr_complex
InputFilter.output_item_type=gr_complex

Resampler.implementation=Pass_Through
Resampler.item_type=gr_complex
Resampler.sample_freq_in=20460000
Resampler.sample_freq_out=20460000


; =========================
; Channels
; =========================
Channels_7X.count=4
Channels.in_acquisition=1
Channel.signal=7X


; =========================
; Acquisition
; =========================
Acquisition_7X.implementation=Galileo_E5b_PCPS_Acquisition
Acquisition_7X.item_type=gr_complex
Acquisition_7X.coherent_integration_time_ms=1
Acquisition_7X.pfa=0.001
Acquisition_7X.doppler_max=6000
Acquisition_7X.doppler_step=100
Acquisition_7X.dump=false
Acquisition_7X.dump_filename=./acq_dump.dat
Acquisition_7X.blocking=false


; =========================
; Tracking
; =========================
Tracking_7X.implementation=Galileo_E5b_DLL_PLL_Tracking
Tracking_7X.item_type=gr_complex

Tracking_7X.extend_correlation_symbols=25

Tracking_7X.pll_bw_hz=30.0
Tracking_7X.dll_bw_hz=10.0
Tracking_7X.pll_bw_narrow_hz=10.0
Tracking_7X.dll_bw_narrow_hz=2.0
Tracking_7X.early_late_space_chips=0.2
Tracking_7X.track_pilot=true
Tracking_7X.dump=false
Tracking_7X.dump_filename=./tracking_ch_

; Tracking_7X.fll_bw_hz=20.0
; Tracking_7X.enable_fll_pull_in=true
; Tracking_7X.enable_fll_steady_state=false
; Tracking_7X.order=3


; =========================
; Telemetry Decoder
; =========================
TelemetryDecoder_7X.implementation=Galileo_E5b_Telemetry_Decoder
TelemetryDecoder_7X.dump=false
TelemetryDecoder_7X.dump_filename=./e5b_telem


; =========================
; Observables
; =========================
Observables.implementation=Hybrid_Observables
Observables.dump=false
Observables.dump_filename=./observables

; enable_carrier_smoothing=true


; =========================
; PVT
; =========================
PVT.implementation=RTKLIB_PVT
PVT.positioning_mode=PPP_Static
; PVT.positioning_mode=Single

PVT.iono_model=Broadcast
PVT.trop_model=Saastamoinen

PVT.output_rate_ms=100
PVT.display_rate_ms=500

PVT.nmea_dump_filename=./gnss_sdr.nmea
PVT.flag_nmea_tty_port=false
PVT.nmea_dump_devname=your_path

PVT.flag_rtcm_server=false
PVT.rtcm_tcp_port=2101
PVT.rtcm_MT1045_rate_ms=5000
PVT.rtcm_MSM_rate_ms=1000

PVT.flag_rtcm_tty_port=false
PVT.rtcm_dump_devname=your_path

PVT.dump=false
PVT.dump_filename=./PVT

PVT.raim_fde=1
PVT.output_enabled=true

PVT.flag_nmea_log_output=false

PVT.min_elevation_deg=10


; =========================
; Monitor
; =========================
Monitor.enable_monitor=false
Monitor.decimation_factor=1
Monitor.client_addresses=127.0.0.1
Monitor.udp_port=1234
